import {
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiTypescript,
  SiJavascript,
  SiPython,
  SiGo,
  SiCplusplus,
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiMongodb,
  SiPostgresql,
  SiRedis,
  SiDocker,
  SiKubernetes,
  SiAmazon,
  SiGooglecloud,
  SiGit,
  SiGithub,
  SiLinux,
  SiUbuntu,
  SiApple,
  SiAndroid,
  SiIos,
  SiFlutter,
  SiDart,
  SiSwift,
  SiKotlin,
  SiSharp,
  SiRust,
  SiPhp,
  SiRuby,
  SiElixir,
  SiScala,
  SiHaskell,
  SiClojure,
  SiErlang,
  SiR,
  SiJulia,
  SiPowers,
  SiTableau,
  SiApachespark,
  SiApachekafka,
  SiElasticsearch,
  SiNeo4J,
  SiInfluxdb,
  SiMariadb,
  SiSqlite,
  SiMysql,
  SiOracle,
  SiFirebase,
  SiSupabase,
  SiPlanetscale,
  SiVercel,
  SiNetlify,
  SiHeroku,
  SiDigitalocean,
  SiCloudflare,
  SiFastapi,
  SiFlask,
  SiDjango,
  SiExpress,
  SiNestjs,
  SiSpring,
  SiLaravel,
  SiAngular,
  SiVuedotjs,
  SiSvelte,
  SiAlpinedotjs,
  SiJest,
  SiCypress,
  SiSelenium,
  SiWebpack,
  SiVite,
  SiGulp,
  SiGrunt,
  SiBabel,
  SiEslint,
  SiPrettier,
  SiSass,
  SiLess,
  SiStyledcomponents,
  SiChakraui,
  SiMui,
  SiAntdesign,
  SiBootstrap,
  SiBulma,
  SiMantine,
  SiNextui,
  SiTauri,
  SiElectron,
} from 'react-icons/si';
import type { JSX } from 'react';

export const blogTechIcons: Record<string, JSX.Element> = {
  // Frontend Frameworks & Libraries
  'React': <SiReact size={16} className="text-blue-400" />,
  'React.js': <SiReact size={16} className="text-blue-400" />,
  'Next.js': <SiNextdotjs size={16} className="text-black dark:text-white" />,
  'Vue.js': <SiVuedotjs size={16} className="text-green-500" />,
  'Angular': <SiAngular size={16} className="text-red-600" />,
  'Svelte': <SiSvelte size={16} className="text-orange-500" />,
  'Alpine.js': <SiAlpinedotjs size={16} className="text-teal-500" />,
  
  // Languages
  'JavaScript': <SiJavascript size={16} className="text-yellow-400" />,
  'TypeScript': <SiTypescript size={16} className="text-blue-600" />,
  'Python': <SiPython size={16} className="text-blue-500" />,
  'Go': <SiGo size={16} className="text-cyan-400" />,
  'Rust': <SiRust size={16} className="text-orange-600" />,
  'C++': <SiCplusplus size={16} className="text-blue-700" />,
  'C#': <SiSharp size={16} className="text-purple-600" />,
  'PHP': <SiPhp size={16} className="text-indigo-500" />,
  'Ruby': <SiRuby size={16} className="text-red-600" />,
  'Swift': <SiSwift size={16} className="text-orange-500" />,
  'Kotlin': <SiKotlin size={16} className="text-purple-500" />,
  'Dart': <SiDart size={16} className="text-blue-400" />,
  'Elixir': <SiElixir size={16} className="text-purple-600" />,
  'Scala': <SiScala size={16} className="text-red-600" />,
  'Haskell': <SiHaskell size={16} className="text-purple-600" />,
  'Clojure': <SiClojure size={16} className="text-green-600" />,
  'Erlang': <SiErlang size={16} className="text-red-600" />,
  'R': <SiR size={16} className="text-blue-600" />,
  'Julia': <SiJulia size={16} className="text-purple-600" />,
 
  // Web Technologies
  'HTML': <SiHtml5 size={16} className="text-orange-500" />,
  'CSS': <SiCss3 size={16} className="text-blue-500" />,
  'HTML/CSS': <SiHtml5 size={16} className="text-orange-500" />,
  'Tailwind CSS': <SiTailwindcss size={16} className="text-cyan-400" />,
  'TailwindCSS': <SiTailwindcss size={16} className="text-cyan-400" />,
  'Sass': <SiSass size={16} className="text-pink-400" />,
  'Less': <SiLess size={16} className="text-blue-600" />,
  'Styled Components': <SiStyledcomponents size={16} className="text-pink-500" />,
  
  // Backend Frameworks
  'Node.js': <SiNodedotjs size={16} className="text-green-600" />,
  'Express': <SiExpress size={16} className="text-gray-600" />,
  'Express.js': <SiExpress size={16} className="text-gray-600" />,
  'NestJS': <SiNestjs size={16} className="text-red-600" />,
  'FastAPI': <SiFastapi size={16} className="text-teal-600" />,
  'Flask': <SiFlask size={16} className="text-gray-700" />,
  'Django': <SiDjango size={16} className="text-green-700" />,
  'Spring': <SiSpring size={16} className="text-green-600" />,
  'Laravel': <SiLaravel size={16} className="text-red-500" />,
  
  // Databases
  'MongoDB': <SiMongodb size={16} className="text-green-500" />,
  'PostgreSQL': <SiPostgresql size={16} className="text-blue-600" />,
  'MySQL': <SiMysql size={16} className="text-blue-600" />,
  'SQLite': <SiSqlite size={16} className="text-blue-500" />,
  'Redis': <SiRedis size={16} className="text-red-600" />,
  'Elasticsearch': <SiElasticsearch size={16} className="text-yellow-600" />,
  'Neo4j': <SiNeo4J size={16} className="text-blue-500" />,
  'InfluxDB': <SiInfluxdb size={16} className="text-blue-500" />,
  'MariaDB': <SiMariadb size={16} className="text-brown-600" />,
  'Oracle': <SiOracle size={16} className="text-red-600" />,
  
  // Cloud & DevOps
  'AWS': <SiAmazon size={16} className="text-orange-500" />,
  'Google Cloud': <SiGooglecloud size={16} className="text-blue-500" />,
  'Docker': <SiDocker size={16} className="text-blue-500" />,
  'Kubernetes': <SiKubernetes size={16} className="text-blue-600" />,
  'Vercel': <SiVercel size={16} className="text-black dark:text-white" />,
  'Netlify': <SiNetlify size={16} className="text-teal-500" />,
  'Heroku': <SiHeroku size={16} className="text-purple-600" />,
  'DigitalOcean': <SiDigitalocean size={16} className="text-blue-500" />,
  'Cloudflare': <SiCloudflare size={16} className="text-orange-500" />,
  
  // Tools & Services
  'Git': <SiGit size={16} className="text-orange-600" />,
  'GitHub': <SiGithub size={16} className="text-gray-700 dark:text-white" />,
  'Firebase': <SiFirebase size={16} className="text-orange-500" />,
  'Supabase': <SiSupabase size={16} className="text-green-500" />,
  'PlanetScale': <SiPlanetscale size={16} className="text-black dark:text-white" />,
  
  // Mobile & Desktop
  'Flutter': <SiFlutter size={16} className="text-blue-400" />,
  'React Native': <SiReact size={16} className="text-blue-400" />,
  'Android': <SiAndroid size={16} className="text-green-500" />,
  'iOS': <SiIos size={16} className="text-gray-700" />,
  'Electron': <SiElectron size={16} className="text-teal-500" />,
  'Tauri': <SiTauri size={16} className="text-yellow-600" />,
  
  // Testing & Build Tools
  'Jest': <SiJest size={16} className="text-red-600" />,
  'Cypress': <SiCypress size={16} className="text-green-600" />,
  'Selenium': <SiSelenium size={16} className="text-green-600" />,
  'Webpack': <SiWebpack size={16} className="text-blue-500" />,
  'ESLint': <SiEslint size={16} className="text-purple-600" />,
  'Prettier': <SiPrettier size={16} className="text-pink-500" />,
  'Babel': <SiBabel size={16} className="text-yellow-500" />,
  
  // UI Libraries
  'Chakra UI': <SiChakraui size={16} className="text-teal-500" />,
  'Material-UI': <SiMui size={16} className="text-blue-500" />,
  'Ant Design': <SiAntdesign size={16} className="text-blue-600" />,
  'Bootstrap': <SiBootstrap size={16} className="text-purple-600" />,
  'Bulma': <SiBulma size={16} className="text-teal-500" />,
  'Mantine': <SiMantine size={16} className="text-blue-500" />,
  'NextUI': <SiNextui size={16} className="text-black dark:text-white" />,
  
  // Data & Analytics
  'Power BI': <SiPowers size={16} className="text-yellow-500" />,
  'Tableau': <SiTableau size={16} className="text-blue-600" />,
  'Apache Spark': <SiApachespark size={16} className="text-orange-500" />,
  'Apache Kafka': <SiApachekafka size={16} className="text-black dark:text-white" />,
  
  // Operating Systems
  'Linux': <SiLinux size={16} className="text-yellow-600" />,
  'Ubuntu': <SiUbuntu size={16} className="text-orange-500" />,
  'macOS': <SiApple size={16} className="text-gray-700" />,
  
  // AI/ML
  'TensorFlow': <SiJavascript size={16} className="text-orange-500" />,
  'PyTorch': <SiJavascript size={16} className="text-red-500" />,
  'OpenAI': <SiJavascript size={16} className="text-green-500" />,
  'Hugging Face': <SiJavascript size={16} className="text-yellow-500" />,
  
  // General/Fallback
  'Web Development': <SiHtml5 size={16} className="text-orange-500" />,
  'Full Stack': <SiJavascript size={16} className="text-yellow-400" />,
  'Backend': <SiNodedotjs size={16} className="text-green-600" />,
  'Frontend': <SiReact size={16} className="text-blue-400" />,
  'DevOps': <SiDocker size={16} className="text-blue-500" />,
  'Mobile': <SiReact size={16} className="text-blue-400" />,
  'API': <SiJavascript size={16} className="text-green-600" />,
  'Database': <SiMongodb size={16} className="text-green-500" />,
  'Security': <SiJavascript size={16} className="text-red-600" />,
  'Performance': <SiJavascript size={16} className="text-orange-500" />,
  'Tutorial': <SiJavascript size={16} className="text-blue-500" />,
  'Guide': <SiJavascript size={16} className="text-green-500" />,
  'Tips': <SiJavascript size={16} className="text-purple-500" />,
  'Best Practices': <SiJavascript size={16} className="text-indigo-500" />,
  'Architecture': <SiJavascript size={16} className="text-gray-600" />,
  'Design Patterns': <SiJavascript size={16} className="text-pink-500" />,
  'Microservices': <SiDocker size={16} className="text-blue-500" />,
  'Serverless': <SiAmazon size={16} className="text-orange-500" />,
  'Machine Learning': <SiPython size={16} className="text-blue-500" />,
  'AI': <SiPython size={16} className="text-green-500" />,
  'Data Science': <SiPython size={16} className="text-blue-600" />,
  'Blockchain': <SiJavascript size={16} className="text-yellow-600" />,
  'Cryptocurrency': <SiJavascript size={16} className="text-orange-600" />,
  'Web3': <SiJavascript size={16} className="text-purple-600" />,
  'IoT': <SiJavascript size={16} className="text-green-600" />,
  'Embedded': <SiCplusplus size={16} className="text-blue-700" />,
  'Game Development': <SiCplusplus size={16} className="text-red-600" />,
  'Computer Graphics': <SiCplusplus size={16} className="text-purple-600" />,
  'Operating Systems': <SiLinux size={16} className="text-yellow-600" />,
  'Networking': <SiJavascript size={16} className="text-blue-600" />,
  'Cybersecurity': <SiJavascript size={16} className="text-red-700" />,
  'Testing': <SiJest size={16} className="text-red-600" />,
  'Automation': <SiJavascript size={16} className="text-green-600" />,
  'CI/CD': <SiGithub size={16} className="text-gray-700" />,
  'Monitoring': <SiJavascript size={16} className="text-orange-600" />,
  'Logging': <SiJavascript size={16} className="text-yellow-600" />,
  'Debugging': <SiJavascript size={16} className="text-red-500" />,
  'Code Review': <SiGithub size={16} className="text-gray-700" />,
  'Open Source': <SiGithub size={16} className="text-black dark:text-white" />,
  'Career': <SiJavascript size={16} className="text-purple-500" />,
  'Interview': <SiJavascript size={16} className="text-blue-500" />,
  'Productivity': <SiJavascript size={16} className="text-green-500" />,
  'Tools': <SiJavascript size={16} className="text-orange-500" />,
  'Resources': <SiJavascript size={16} className="text-indigo-500" />,
  'News': <SiJavascript size={16} className="text-red-500" />,
  'Updates': <SiJavascript size={16} className="text-blue-500" />,
  'Release': <SiJavascript size={16} className="text-green-500" />,
  'Announcement': <SiJavascript size={16} className="text-purple-500" />,
  'Opinion': <SiJavascript size={16} className="text-orange-500" />,
  'Discussion': <SiJavascript size={16} className="text-pink-500" />,
  'Comparison': <SiJavascript size={16} className="text-teal-500" />,
  'Review': <SiJavascript size={16} className="text-indigo-500" />,
};